#!/bin/bash

read -d '' USAGE<<EOF

     course_info <option>
     options are:

     i)  displays all student login-ids
     n)  displays number of students
     t)  displays the login-id of the instructor
     a)  displays all of the above
     h)  displays the help menu

     Examples:

     course_info -i 35690

     will display the login-ids of all
     of the students in the class
     with the CRN number 35690.

     course_info -t 43578

     will display the login-ids
     of the instructor of the class
     with the CRN number 43578.

     course_info -n 43432

     will display the number of students
     in the class represented
     by the CRN number 43432.

EOF

is_crn_in_proper_format () {
    REGEX0='^c[0-9]{5}'
    if [[ ! ${CRN} =~ ${REGEX0} ]]
    then
	echo "Improper CRN format with ${OPTARG}!"
	echo "At CCSF, each course is represented by a unique 5-digit number."
	echo "This number is called \"CRN\". For example 32569 is a CRN number."
	exit 999
    fi
}

does_crn_exist () {
    is_crn_in_proper_format ${CRN}
    RESULT=$(grep -P "^${CRN}" /etc/group)
    if [ ${#RESULT} == 0 ]; then
	echo "CRN ${OPTARG} does not exist!" && exit 999
    fi
}

process_result () {
    IFS=':' read -ra temp_array <<< ${RESULT}
    IFS="," read -ra members_array <<< ${temp_array[3]}
}

prep () {
    CRN="c${OPTARG}"
    does_crn_exist ${CRN}
    process_result ${RESULT}
}    

student_login_ids () {
    printf "student login-ids of CRN ${CRN}:\n\n"
    for ((i=1; i<=(${#members_array[@]}-1);i++))
    do
	echo "${members_array[${i}]}"
    done
}

number_of_students () {
    printf "The number of students of CRN ${CRN}:\n\n"
    student_count=${#members_array[@]}
    student_count=$((student_count-1))
    echo "${student_count}"
}

login_id_of_instructor () {
    printf "login id of instructor of CRN ${CRN}:\n\n"
    echo "${members_array[0]}"
}


while getopts i:n:t:a:h flag
do
    case "${flag}" in
	h) printf "\n     ${USAGE}\n\n" && exit;;
	a) prep && login_id_of_instructor && \
		 number_of_students && \
		 student_login_ids && exit;;
	t) prep && login_id_of_instructor && exit;;
	n) prep && number_of_students && exit;;
	i) prep && student_login_ids && exit;;
	?) printf "INVALID OPTION!\n\n     ${USAGE}\n\n" && exit;;
    esac
done

printf "\n     ${USAGE}\n\n"
